### ISSUE TITLE
Publish new fully translated languages

### ISSUE THREAD

**Issue by Pablohn26** [Plailect/Guide_Vita#16]
I can see on Crowdin several languages that are 100% translated but there are not published. 

Current published languages: 
* English
* Russian
* Chinese Traditional

Non published 100% translated languages:
* German
* Italian
* Portuguese
* Spanish

Could you update the website to make available translated languages?

**Comment by Plailect** [comment]
Of the listed languages, only Spanish has actually been proofread (a requirement for publishing). I will add that one though.

**Comment by Plailect** [comment]
fixed
